### ISSUE TITLE
main.hbs bulunamadı.

### ISSUE THREAD

**Issue by alialaca** [ipara/ipara-nodejs#7]
Merhaba,

localhost:3000 adresine girdiğimde aşağıdaki hatayı almaktayım:
`Error: ENOENT: no such file or directory, open '<project_folder>\views\layouts\main.hbs'`

**main.hbs** dosyasının ben de bulamadığım gibi ilgili dosyanın çağrıldığı kod satırını da bulamadım.
Uygulama güncel ?

**Comment by frkn-aydn** [comment]
Sanırım sorun çözülmüş. 

Eski versiyonu kullananların tek yapması gereken : router/app.js içerisindeki render etmek istediği route a {layout: false} eklemek. Bu option ile layout klasörüne bakmayacaktır.

**Comment by alialaca** [comment]
Evet çözdüm, yeni versiyondan da haberim yoktu. Teşekkürler.
